# Generated by Django 6.0.3 on 2026-03-11 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_council_id', models.CharField(help_text='Bar Council Registration Number', max_length=50, unique=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True, help_text='Professional biography')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Consultation fee in INR', max_digits=10)),
                ('office_address', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('is_available', models.BooleanField(default=True, help_text='Is the lawyer currently accepting appointments?')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('verification_document', models.FileField(blank=True, help_text='Upload bar council certificate or ID', null=True, upload_to='lawyer_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specializations', models.ManyToManyField(blank=True, related_name='lawyers', to='categories.legalcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lawyer Profile',
                'verbose_name_plural': 'Lawyer Profiles',
                'db_table': 'lawyer_profiles',
                'ordering': ['-rating', '-experience_years'],
            },
        ),
        migrations.CreateModel(
            name='LawyerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='lawyers.lawyerprofile')),
            ],
            options={
                'verbose_name': 'Availability Slot',
                'verbose_name_plural': 'Availability Slots',
                'db_table': 'lawyer_availability',
                'ordering': ['day', 'start_time'],
                'unique_together': {('lawyer', 'day', 'start_time')},
            },
        ),
    ]
